function t(e){return t="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(t){return typeof t}:function(t){return t&&"function"==typeof Symbol&&t.constructor===Symbol&&t!==Symbol.prototype?"symbol":typeof t},t(e)
/**
** Javascript
** 放大镜脚本
** Author： Tance Tui.txh (Tuxiaohua)
** webSite: https://github.com/Timtance
** js: https://www.npmjs.com/package/ti-zoom
** version: 1.2.0
**/}window.tuiZoom=function(e){var o=1,n=100,i=.5,l={},s=1,a=1,d=document.createElement("canvas"),r=d.getContext("2d"),u=null,f=null;d.className="tuiZoomCanvas",d.style.cssText="opacity: 1;position: relative; border: none; border-radius: 50%; z-index: 2;",d.width=n/i,d.height=n/i;var c=document.createElement("div");function m(){c.style.display="none",d.style.display="none"}c.className="tuiZoomCanvasElement",c.style.cssText="position: absolute;display: flex;z-index: 10; padding: 5px; border-radius: 50%;cursor: none;background-image: -webkit-linear-gradient(-315deg, #ee7f6e, #c878b8);",c.append(d),document.body.append(c),e=e||"targetDiv",this.setBoxObjZoom=function(t){o=t},this.setTarget=function(t){if(t&&("string"==typeof t?u=document.getElementById(t):(u=t,t.id||(t.id="tuiZoom_"+Math.random()),t=t.id),u)){if("IMG"!=u.tagName)return void(u=null);a=u.naturalHeight!=u.offsetHeight?u.naturalHeight/u.offsetHeight:1,s=u.naturalWidth!=u.offsetWidth?u.naturalWidth/u.offsetWidth:1,f=u.getBoundingClientRect()}},this.setTarget(e),this.setZoomRate=function(t){i=t,d.width=n/i,d.height=n/i},this.destroy=function(){u=null,window.onmousemove=null,c.removeChild(d),document.body.removeChild(c)},this.setZoomStyle=function(e){"object"===t(e)&&Object.keys(e).forEach((function(t){d.style[t]=e[t]}))},window.onmousemove=function(t){if(u){var e=t.clientX,i=t.clientY;e>=f.left*o&&e<=f.right*o&&i>=f.top*o&&i<=f.bottom*o?function(t,e){l.left=((t-0)*s-50)/o,l.top=((e-0)*a-50)/o,function(t,e){c.style.left=t-d.width/2+"px",c.style.top=e-d.height/2+"px",c.style.display="flex",d.style.display="inline",r.drawImage(u,l.left-f.left*s,l.top-f.top*a,n,n,0,0,d.width,d.height)}(t,e)}(e,i):m()}},m()};
