function t(e){return t="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(t){return typeof t}:function(t){return t&&"function"==typeof Symbol&&t.constructor===Symbol&&t!==Symbol.prototype?"symbol":typeof t},t(e)
/**
** Javascript
** 放大镜脚本
** Author： Tance Tui.txh (Tuxiaohua)
** webSite: https://github.com/Timtance
** js: https://www.npmjs.com/package/ti-zoom
** version: 1.2.3
**/}window.tuiZoom=function(e){var o=1,n=100,i=.5,l={},s=1,u=1,c=0,a=0,r=document.createElement("canvas"),h=r.getContext("2d"),d=null,f=null,m=0;r.className="tuiZoomCavans",r.style.cssText="opacity: 1;position: relative; border: none; border-radius: 50%; z-index: 2;",r.width=n/i,r.height=n/i;var y=document.createElement("div");y.className="tuiZoomCanvasElement",y.style.cssText="position: absolute;display: flex;z-index: 10; padding: 5px; border-radius: 50%;cursor: none;background-image: -webkit-linear-gradient(-315deg, #ee7f6e, #c878b8);",y.append(r),document.body.append(y),e=e||"targetDiv";var p=0,g=0;function b(t){if(d){if("touchstart"===t.type)return void(2===t.touches.length&&(m=Math.hypot(t.touches[0].clientX-t.touches[1].clientX,t.touches[0].clientY-t.touches[1].clientY)));if("touchmove"===t.type){if(2===t.touches.length){var e=Math.hypot(t.touches[0].clientX-t.touches[1].clientX,t.touches[0].clientY-t.touches[1].clientY),n=Math.floor(e/m);this.setZoomRate(setZoomRate(n))}t=t.touches[0]}var i=t.clientX,l=t.clientY;p=i,g=l,i>=f.left*o&&i<=f.right*o&&l>=f.top*o&&l<=f.bottom*o?x(i,l):v()}}function v(){y.style.display="none",r.style.display="none"}function w(){return n/2}function x(t,e){l.left=((t-c)*s-w())/o,l.top=((e-a)*u-w())/o,function(t,e){y.style.left=t-r.width/2+"px",y.style.top=e-r.height/2+"px",y.style.display="flex",r.style.display="inline",h.drawImage(d,l.left-f.left*s,l.top-f.top*u,n,n,0,0,r.width,r.height)}(t,e)}this.setBoxObjZoom=function(t){t&&(o=t)},this.setTarget=function(t){if(t&&("string"==typeof t?d=document.getElementById(t):(d=t,t.id||(t.id="tuiZoom_"+Math.random()),t=t.id),d)){if("IMG"!=d.tagName)return void(d=null);u=d.naturalHeight!=d.offsetHeight?d.naturalHeight/d.offsetHeight:1,s=d.naturalWidth!=d.offsetWidth?d.naturalWidth/d.offsetWidth:1,f=d.getBoundingClientRect()}},this.setTarget(e),this.setZoomRate=function(t){r.width=n/i*t,r.height=n/i*t,x(p,g)},this.destroy=function(){d=null,window.onmousemove=null,window.ontouchmove=null,y.removeChild(r),document.body.removeChild(y)},this.setZoomStyle=function(e){"object"===t(e)&&Object.keys(e).forEach((function(t){r.style[t]=e[t]}))},window.onmousemove=b,window.ontouchmove=b,window.ontouchstart=b,v()};
