var t;t=function(){function t(e){return t="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(t){return typeof t}:function(t){return t&&"function"==typeof Symbol&&t.constructor===Symbol&&t!==Symbol.prototype?"symbol":typeof t},t(e)
/**
  ** Javascript
  ** 放大镜脚本
  ** Author： Tance Tui.txh (Tuxiaohua)
  ** webSite: https://github.com/Timtance
  ** js: https://www.npmjs.com/package/ti-zoom
  ** version: 1.2.0
  **/}window.tuiZoom=function(e){var o=1,n=100,i=.5,l={},a=1,d=1,s=document.createElement("canvas"),u=s.getContext("2d"),f=null,r=null;s.className="tuiZoomCanvas",s.style.cssText="opacity: 1;position: relative; border: none; border-radius: 50%; z-index: 2;",s.width=n/i,s.height=n/i;var c=document.createElement("div");function m(){c.style.display="none",s.style.display="none"}c.className="tuiZoomCanvasElement",c.style.cssText="position: absolute;display: flex;z-index: 10; padding: 5px; border-radius: 50%;cursor: none;background-image: -webkit-linear-gradient(-315deg, #ee7f6e, #c878b8);",c.append(s),document.body.append(c),e=e||"targetDiv",this.setBoxObjZoom=function(t){o=t},this.setTarget=function(t){if(t&&("string"==typeof t?f=document.getElementById(t):(f=t,t.id||(t.id="tuiZoom_"+Math.random()),t=t.id),f)){if("IMG"!=f.tagName)return void(f=null);d=f.naturalHeight!=f.offsetHeight?f.naturalHeight/f.offsetHeight:1,a=f.naturalWidth!=f.offsetWidth?f.naturalWidth/f.offsetWidth:1,r=f.getBoundingClientRect()}},this.setTarget(e),this.setZoomRate=function(t){i=t,s.width=n/i,s.height=n/i},this.destroy=function(){f=null,window.onmousemove=null,c.removeChild(s),document.body.removeChild(c)},this.setZoomStyle=function(e){"object"===t(e)&&Object.keys(e).forEach((function(t){s.style[t]=e[t]}))},window.onmousemove=function(t){if(f){var e=t.clientX,i=t.clientY;e>=r.left*o&&e<=r.right*o&&i>=r.top*o&&i<=r.bottom*o?function(t,e){l.left=((t-0)*a-50)/o,l.top=((e-0)*d-50)/o,function(t,e){c.style.left=t-s.width/2+"px",c.style.top=e-s.height/2+"px",c.style.display="flex",s.style.display="inline",u.drawImage(f,l.left-r.left*a,l.top-r.top*d,n,n,0,0,s.width,s.height)}(t,e)}(e,i):m()}},m()}},"function"==typeof define&&define.amd?define(t):t();
